apiVersion: batch/v1
kind: Job
metadata:
  name: html-deploy
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: html-deploy-container
        image: mktfe.azurecr.io/f1-cn
        command: ["rsync", "-avh", "/newData/", "/srcData/"]
        volumeMounts:
          - mountPath: "/srcData"
            name: pvc
      restartPolicy: Never
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: az-file-premium-pvc-f1dev-master
