apiVersion: v1
kind: Pod
metadata:
  name: html-deploy-f1dev-master
spec:
  containers:
  - name: html-deploy-container
    image: mktfe.azurecr.io/will-be-replaced
    command: ["rsync", "-avh", "/newData/", "/srcData/"]
    volumeMounts:
      - mountPath: "/srcData"
        name: pvc
  restartPolicy: Never
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: az-file-premium-pvc-f1dev-master
